//user
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const GET_JOBS = "GET_JOBS";
export const GET_CLIENT_JOBS = "GET_CLIENT_JOBS";
export const GET_CLIENT_JOBS_APPLICANTS = "GET_CLIENT_JOBS_APPLICANTS";
export const GET_WORKER_APPLIED_JOBS = "GET_WORKER_APPLIED_JOBS";
export const GET_SERVICES = "GET_SERVICES";
